### ISSUE TITLE
Cannot read property 'scheme' of undefined

### ISSUE THREAD

**Issue by mike-aungsan** [domenic/restify-oauth2#31]
ServerHandler:log TypeError: Cannot read property 'scheme' of undefined
    at Server.ccOAuth2Plugin (/home/mike_api/node_modules/restify-oauth2/lib/common/makeSetup.js:55:41)
    at next (/home/mike_api/node_modules/restify/lib/server.js:745:30)
    at f (/home/mike_api/node_modules/restify/node_modules/once/once.js:17:25)
    at Server.bunyan (/home/mike_api/node_modules/restify/lib/plugins/bunyan.js:36:9)
    at next (/home/mike_api/node_modules/restify/lib/server.js:745:30)
    at f (/home/mike_api/node_modules/restify/node_modules/once/once.js:17:25)
    at Server.restifyResponseHeaders (/home/mike_api/node_modules/restify/lib/plugins/full_response.js:97:17)
    at next (/home/mike_api/node_modules/restify/lib/server.js:745:30)
    at f (/home/mike_api/node_modules/restify/node_modules/once/once.js:17:25)
    at Server.restifyCORSSimple (/home/mike_api/node_modules/restify/lib/plugins/cors.js:95:13) +0ms

**Comment by gmaniac** [comment]
I will look into this today, sorry for the delay. I will let you know if I figure anything out.

**Comment by mike-aungsan** [comment]
Many Thanks. I think I fix it this one. This is my mistakes why learning this module :)

**Comment by synth3tk** [comment]
What was the fix you had? I'm also running into this.

**Comment by synth3tk** [comment]
Nevermind, figured it out. In my case, I forgot to include `server.use(restify.authorizationParser());`.
